name: HCare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0
  shared_preferences: ^0.5.12+4
  auto_size_text: ^1.1.2
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  table_calendar: ^2.3.1
  http: ^0.12.1
  url_launcher: ^3.0.0
  crypto: ^2.0.0
  image_picker: 0.6.7+2
  flutter_slidable: ^0.5.7
  mailer: ^2.0.0


  firebase_messaging: ^7.0.3

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  simple_animations: ^3.1.1
  animated_text_kit: ^4.2.1
  awesome_dialog: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0


flutter_icons:
  android: true
  ios: true
  image_path: "icons/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/images/
   - assets/student.png
   - assets/doctor1.png
   - assets/doctor2.jpg
   - assets/doctor3.jpg
   - assets/doctor5.png
   - assets/doctor6.png
   - assets/doctor7.jpg
   - assets/user.png
   - assets/Teacher11.png
   - assets/Teacher.png
   - assets/teacher2.png
   - assets/images/English.jpg
   - assets/images/Math.jpg
   - assets/images/Arabic.jpg
   - assets/images/Science.jpg
   - assets/images/login.jpg
   - assets/images/login_bottom.png
   - assets/images/main_top.png
   - assets/images/login1.jpeg
   - assets/images/background.jpg
   - assets/images/logos.png
   - assets/images/logo.jpg
   - assets/images/GeneralMedicine.webp
   - assets/images/GeneralMedicine.jpg
   - assets/images/NaturalTherapy.webp
   - assets/images/NaturalTherapy.jpg
   - assets/images/OccupationalTherapy.webp
   - assets/images/OccupationalTherapy.jpeg
   - assets/images/HomeNursing.webp
   - assets/images/HomeNursing.jpg
   - assets/onboarding.png
   - assets/student-icon.png
   - assets/emergency-people-icon.png
   - assets/medication-icon.png
   - assets/activites-icon.png
   - assets/time-table-icon.png
   - assets/fees-icon.png
   - assets/child-feedback-icon.png
   - assets/time-table-icon.png
   - assets/tasks-icon.png
   - assets/class-icon.png
   - assets/complaint-icon.png
   - assets/logout-icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
